### ISSUE TITLE
请问能否支持自动更新？

### ISSUE THREAD

**Issue by xpysgdhr** [TinkMingKing/siyuan-index-plugins#2]
这个插件很好用！但是有一个问题，就是如果创建新的子文档，目录不会自动刷新。而obsidian的waypoint就可以自动更新，这个大佬能否实现下哈，非常期待！

**Comment by TinkMingKing** [comment]
> 这个插件很好用！但是有一个问题，就是如果创建新的子文档，目录不会自动刷新。而obsidian的waypoint就可以自动更新，这个大佬能否实现下哈，非常期待！

可以试试，但暂时别抱太大期待

**Comment by TinkMingKing** [comment]
思源好像没有相关的api，我会去参考一下你说的这个插件是如何实现的，这里是旧版非官方插件系统的仓库，更新到siyuan最新版有官方插件仓库，后续有问题请转到这里反馈[目录插件](https://github.com/TinkMingKing/siyuan-plugins-index/issues/8)，这里我先关了
